from __future__ import annotations

from typing import Any, Callable, TypedDict
from functools import wraps

from flask import Blueprint, current_app, jsonify, request

from .db import get_database_connection
from .autoblog import upsert_feed, list_feeds, ingest_all_feeds, ingest_feed, ensure_autobot_user


bp = Blueprint("api", __name__, url_prefix="/api")


def api_key_required(view_func: Callable[..., Any]):
    @wraps(view_func)
    def wrapper(*args, **kwargs):
        api_key = request.headers.get("X-API-Key") or request.args.get("api_key")
        expected = current_app.config.get("API_KEY")
        if not expected or api_key != expected:
            return jsonify({"error": "unauthorized"}), 401
        return view_func(*args, **kwargs)

    return wrapper


class PostPayload(TypedDict, total=False):
    title: str
    body: str
    author_username: str


@bp.post("/posts")
@api_key_required
def create_post():
    payload: PostPayload = request.get_json(silent=True) or {}
    title = (payload.get("title") or "").strip()
    body = (payload.get("body") or "").strip()
    author_username = (payload.get("author_username") or "autobot").strip() or "autobot"
    if not title or not body:
        return jsonify({"error": "title and body are required"}), 400
    db_conn = get_database_connection()

    # get or create author
    from werkzeug.security import generate_password_hash

    user_row = db_conn.execute("SELECT id FROM user WHERE username = ?", (author_username,)).fetchone()
    if not user_row:
        db_conn.execute(
            "INSERT INTO user (username, password) VALUES (?, ?)",
            (author_username, generate_password_hash("autogenerated")),
        )
        db_conn.commit()
        user_row = db_conn.execute("SELECT id FROM user WHERE username = ?", (author_username,)).fetchone()

    db_conn.execute(
        "INSERT INTO post (author_id, title, body) VALUES (?, ?, ?)",
        (int(user_row["id"]), title, body),
    )
    db_conn.commit()
    new_id = int(db_conn.execute("SELECT last_insert_rowid() AS id").fetchone()["id"])  # type: ignore[index]
    return jsonify({"id": new_id, "title": title}), 201


@bp.post("/feeds")
@api_key_required
def add_feed():
    data = request.get_json(silent=True) or {}
    url = (data.get("url") or "").strip()
    title = (data.get("title") or None)
    if not url:
        return jsonify({"error": "url is required"}), 400
    feed_id = upsert_feed(url, title)
    return jsonify({"id": feed_id, "url": url}), 201


@bp.get("/feeds")
@api_key_required
def get_feeds():
    return jsonify({"feeds": list(list_feeds())})


@bp.post("/ingest")
@api_key_required
def ingest():
    data = request.get_json(silent=True) or {}
    feed_id = data.get("feed_id")
    if feed_id is not None:
        result = ingest_feed(int(feed_id))
        return jsonify(result)
    result = ingest_all_feeds()
    return jsonify(result)

