from __future__ import annotations

from typing import Any, Iterable
import re
import html

import feedparser  # type: ignore

from .db import get_database_connection


def strip_html(html_text: str) -> str:
    text = re.sub(r"<[^>]+>", "", html_text)
    return html.unescape(text).strip()


def ensure_autobot_user(username: str = "autobot") -> int:
    from werkzeug.security import generate_password_hash

    db_conn = get_database_connection()
    row = db_conn.execute("SELECT id FROM user WHERE username = ?", (username,)).fetchone()
    if row:
        return int(row["id"])  # type: ignore[index]
    db_conn.execute(
        "INSERT INTO user (username, password) VALUES (?, ?)",
        (username, generate_password_hash("autogenerated")),
    )
    db_conn.commit()
    return int(db_conn.execute("SELECT id FROM user WHERE username = ?", (username,)).fetchone()["id"])  # type: ignore[index]


def upsert_feed(url: str, title: str | None = None) -> int:
    db_conn = get_database_connection()
    db_conn.execute(
        "CREATE TABLE IF NOT EXISTS feed (id INTEGER PRIMARY KEY AUTOINCREMENT, url TEXT UNIQUE NOT NULL, title TEXT, etag TEXT, modified TEXT, last_fetched TIMESTAMP)"
    )
    db_conn.commit()
    existing = db_conn.execute("SELECT id FROM feed WHERE url = ?", (url,)).fetchone()
    if existing:
        return int(existing["id"])  # type: ignore[index]
    db_conn.execute("INSERT INTO feed (url, title) VALUES (?, ?)", (url, title))
    db_conn.commit()
    row = db_conn.execute("SELECT id FROM feed WHERE url = ?", (url,)).fetchone()
    return int(row["id"])  # type: ignore[index]


def list_feeds() -> Iterable[dict[str, Any]]:
    db_conn = get_database_connection()
    rows = db_conn.execute("SELECT id, url, title, etag, modified, last_fetched FROM feed ORDER BY id").fetchall()
    return [dict(row) for row in rows]


def ingest_feed(feed_id: int) -> dict[str, Any]:
    db_conn = get_database_connection()
    feed_row = db_conn.execute("SELECT * FROM feed WHERE id = ?", (feed_id,)).fetchone()
    if not feed_row:
        return {"feed_id": feed_id, "created": 0, "skipped": 0, "error": "feed not found"}

    etag = feed_row["etag"]
    modified = feed_row["modified"]
    parsed = feedparser.parse(feed_row["url"], etag=etag, modified=modified)

    created_count = 0
    skipped_count = 0
    author_id = ensure_autobot_user()

    # Ensure schema for source_url unique (idempotent)
    try:
        cols = [r[1] for r in db_conn.execute("PRAGMA table_info(post)").fetchall()]
        if "source_url" not in cols:
            db_conn.execute("ALTER TABLE post ADD COLUMN source_url TEXT")
            db_conn.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS ux_post_source_url ON post(source_url)"
            )
            db_conn.commit()
    except Exception:
        pass

    for entry in parsed.entries:
        link = entry.get("link")
        title = entry.get("title") or "Untitled"
        summary = entry.get("summary") or entry.get("description") or ""
        body = strip_html(summary)[:5000]
        if not link:
            # compose a pseudo-unique source when missing link
            link = f"feed:{feed_row['url']}#title:{title}"

        exists = db_conn.execute("SELECT id FROM post WHERE source_url = ?", (link,)).fetchone()
        if exists:
            skipped_count += 1
            continue

        db_conn.execute(
            "INSERT INTO post (author_id, title, body, source_url) VALUES (?, ?, ?, ?)",
            (author_id, title, body, link),
        )
        created_count += 1

    db_conn.execute(
        "UPDATE feed SET etag = ?, modified = ?, last_fetched = CURRENT_TIMESTAMP WHERE id = ?",
        (getattr(parsed, "etag", None) or parsed.feed.get("etag"), getattr(parsed, "modified", None) or parsed.feed.get("modified"), feed_id),
    )
    db_conn.commit()

    return {"feed_id": feed_id, "created": created_count, "skipped": skipped_count}


def ingest_all_feeds() -> dict[str, Any]:
    results: list[dict[str, Any]] = []
    for feed in list_feeds():
        results.append(ingest_feed(int(feed["id"])))  # type: ignore[index]
    return {"results": results}

